spring:
  datasource:
    url: "jdbc:postgresql://ec2-54-159-138-67.compute-1.amazonaws.com:5432/dcblgfvhghf4lc"
    driverClassName: org.postgresql.Driver
    username: nvymfgadhxpfja
    password: fbe77ba7ae4d2a35d565f1c766c1b0a0fe00add669fdc58c499488bb1f68a7ac
  jpa:
    hibernate:
      ddl-auto: create

bg:
  time:
    expiration_min: 5
    remove-cron: "0 0/2 * * * *"
    available-cron: "0 0/30 * * * *"
