spring:
  datasource:
    url: "jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/postgres"
    driverClassName: org.postgresql.Driver
    username: adminapp
    password: adminapp
  jpa:
    hibernate:
      ddl-auto: update
bg:
  time:
    expiration_min: 5
    remove-cron: "0 0/5 * * * *"
    available-cron: "0 * 0/1 * * *"
