spring:
  datasource:
    url: "jdbc:postgresql://ec2-54-237-135-248.compute-1.amazonaws.com:5432/dbc3hok93d5fnk"
    driverClassName: org.postgresql.Driver
    username: amabrdknrdfnvy
    password: 089a2f3d631f3b8b200e85cd6cb99465b63cb34be22e6e1cc376b98c70d1c249
  jpa:
    hibernate:
      ddl-auto: create

bg:
  time:
    expiration_min: 5
    cron: "0 0/2 * * * *"